### ISSUE TITLE
Hide 0 balances from Richest Addresses

### ISSUE THREAD

**Issue by carlosmmelo** [wiringbits/block-explorer#1]
Hide 0 balances from Richest Addresses.

@durkmurder Alex had a great question about this:

"what about addresses that had coins but they are spent?"

**Comment by durkmurder** [comment]
We shouldn't track addresses that are spent. 
We have UTXO set, balance of address, is sum of UTXOs, if something is spent, it's not in UTXO set. 
So we shouldn't count anything that was spent

**Comment by AlexITC** [comment]
This has been fixed by e9eb79b813b.
