### ISSUE TITLE
Update Logo to the rebranded one

### ISSUE THREAD

**Issue by carlosmmelo** [wiringbits/block-explorer#10]
Please contact Andriy (designer) for links.

### Expected behavior

As part of today's launch, We should match our rebranded logo.

### Actual behavior

We are displaying the old logo.

### Steps to reproduce the behavior

1. navigate to the explorer: https://xsnexplorer.io/
2. Notice the logo.

**Comment by AlexITC** [comment]
@carlosmmelo  is this something that needs to be done and released today?

**Comment by carlosmmelo** [comment]
@AlexITC no, it could wait for the next release; its not urgent.

**Comment by AlexITC** [comment]
Great, it's better to release having more changes.

In any case, in case you want to make a pull request, this is the logo: https://github.com/X9Developers/block-explorer/blob/master/web-ui/src/assets/stakenet.png

**Comment by carlosmmelo** [comment]
sure, will check with Andriy about the logo file.

**Comment by AlexITC** [comment]
The logo and the favicon were updated on b0481b0f4588.
