### ISSUE TITLE
Adjust the logo dimensions to keep it rounded

### ISSUE THREAD

**Issue by AlexITC** [wiringbits/block-explorer#17]
The logo is getting stretched, we need to keep it rounded.

### Expected behavior

The logo is rounded.

### Actual behavior

The logo is stretched:
![example](https://media.discordapp.net/attachments/426080585891446784/454680792350588928/image.png?width=263&height=468)

### Steps to reproduce the behavior

Go to https://xsnexplorer.io/

**Comment by mario128mex** [comment]
done, screenshots added

**Comment by AlexITC** [comment]
This has been fixed by #22
