### ISSUE TITLE
Allow searching Masternode by IP Address

### ISSUE THREAD

**Issue by carlosmmelo** [wiringbits/block-explorer#3]
Like address, transaction and blockhash; now that we have added a Masternode tab, we should allow users to search a MN by its IP address:

![image](https://user-images.githubusercontent.com/5649650/39163015-881d2f72-4746-11e8-8255-96190f03c202.png)

**Comment by AlexITC** [comment]
On 6e6ed7abb, an endpoint was added to retrieve an specific masternode by ip address.

**Comment by AlexITC** [comment]
On 8cc47045f, the ui was updated to let users find a masternode by ip address.
