### ISSUE TITLE
Transaction format issue, unexpected error

### ISSUE THREAD

**Issue by xhiroz** [wiringbits/block-explorer#46]
Some tx gives unexpected errors. Raw data of it loads though.

### Expected behavior

Shouldn't give any error since it's a valid tx.

### Actual behavior

Gives unexpected error from the XSN network and TX not found.

### Steps to reproduce the behavior

Open: http://xsnexplorer.io/transactions/a27b5e0bf7ed19b4d0bd038029a474fef0e4ccb1543544ff7f4263862d3faab7

Raw data loads though.

**Comment by AlexITC** [comment]
This occurs because there were breaking changes on the transaction format retrieved from the `xsnd`, it should be fixed soon.

Thanks!

**Comment by AlexITC** [comment]
It turned out that the explorer overloaded the `xsnd` while loading this transaction because it has a lot of inputs, updating the `xsnd` configuration was enough to let the explorer display it.
