### ISSUE TITLE
Resolve GitHub vulnerability warning related to angular 

### ISSUE THREAD

**Issue by AlexITC** [wiringbits/block-explorer#55]
Resolve github vulnerability warning on the web-ui project

### Expected behavior

There is no vulnerability warning on the GitHub project page.

### Actual behavior

GitHub is displaying a vulnerability warning that seems to be related to the angular build tools.
![explorer](https://user-images.githubusercontent.com/4218436/46389708-db33de80-c690-11e8-91cc-1f573d881216.png)

### Steps to reproduce the behavior

1. Fork the repository.
2. Go to the forked repository page.
3. The warning will be displayed.

**Comment by rishacha** [comment]
I cannot view any vulnerability alert. Do I have access?

**Comment by AlexITC** [comment]
Interesting, probably it is viewable to owners only, the way to solve it is basically upgrading dependencies.

**Comment by esuau** [comment]
I think the best solution would be to [upgrade your Angular version to 6.1](https://update.angular.io/). I can manage this if you want.

**Comment by AlexITC** [comment]
That would be great.
