### ISSUE TITLE
Update the logback.xml to log exceptions root cause first

### ISSUE THREAD

**Issue by AlexITC** [wiringbits/block-explorer#57]
Update the [logback.xml](https://github.com/X9Developers/block-explorer/blob/develop/server/conf/logback.xml) to [log exceptions root cause first](https://www.nurkiewicz.com/2011/09/logging-exceptions-root-cause-first.html)

### Expected behavior

When an exception is thrown and it has nested causes, the root cause should be the first displayed exception.

### Actual behavior

When an exception is thrown and it has nested causes, the root cause is not the first displayed exception. 

### Steps to reproduce the behavior

Shutting the xsnd or postgres off and leaving the project running show start displaying exceptions.

**Comment by rishacha** [comment]
Hi, can I take this up?

**Comment by AlexITC** [comment]
Of course!

Be sure to follow the [contributing guidelines](https://github.com/X9Developers/block-explorer/blob/develop/CONTRIBUTING.md) please.
